-- Wire network rule + secrets for SPCS job containers.
-- Create secrets first (spcs/create_secrets.sh), then run this.

USE ROLE ACCOUNTADMIN;

CREATE OR REPLACE EXTERNAL ACCESS INTEGRATION ${BEXIO_EAI}
  ALLOWED_NETWORK_RULES = (${DB_NAME}.${SCHEMA}.BEXIO_API_RULE)
  ALLOWED_AUTHENTICATION_SECRETS = (
    ${DB_NAME}.${SCHEMA}.BEXIO_CLIENT_ID,
    ${DB_NAME}.${SCHEMA}.BEXIO_CLIENT_SECRET,
    ${DB_NAME}.${SCHEMA}.BEXIO_REFRESH_TOKEN,
    ${DB_NAME}.${SCHEMA}.DLT_SNOWFLAKE_PASSWORD
  )
  ENABLED = TRUE
  COMMENT = 'Bexio OAuth + Snowflake loader credentials for bexio-dlt-connector (${ENV_UPPER})';

GRANT USAGE ON INTEGRATION ${BEXIO_EAI} TO ROLE ${DEPLOYER_ROLE};
GRANT USAGE ON INTEGRATION ${BEXIO_EAI} TO ROLE ${OPERATOR_ROLE};
