-- Run AFTER deploy_infra.sh + deploy_job.sh for **Snowpipe** job (no DLT_SNOWFLAKE_PASSWORD secret).
-- For dlt + warehouse jobs, use grant_operator_post_deploy.sql instead.
--
-- envsubst < spcs/sql/grant_operator_post_deploy_snowpipe.sql | snow sql -c <connection>

USE ROLE ACCOUNTADMIN;

GRANT USAGE ON COMPUTE POOL ${COMPUTE_POOL} TO ROLE ${OPERATOR_ROLE};
GRANT USAGE ON INTEGRATION ${BEXIO_EAI} TO ROLE ${OPERATOR_ROLE};

GRANT USAGE ON SERVICE ${DB_NAME}.${SCHEMA}.${JOB_SERVICE} TO ROLE ${OPERATOR_ROLE};
GRANT MONITOR ON SERVICE ${DB_NAME}.${SCHEMA}.${JOB_SERVICE} TO ROLE ${OPERATOR_ROLE};

GRANT READ ON SECRET ${DB_NAME}.${SCHEMA}.BEXIO_CLIENT_ID TO ROLE ${OPERATOR_ROLE};
GRANT READ ON SECRET ${DB_NAME}.${SCHEMA}.BEXIO_CLIENT_SECRET TO ROLE ${OPERATOR_ROLE};
GRANT READ ON SECRET ${DB_NAME}.${SCHEMA}.BEXIO_REFRESH_TOKEN TO ROLE ${OPERATOR_ROLE};
GRANT READ ON SECRET ${DB_NAME}.${SCHEMA}.SNOWPIPE_PRIVATE_KEY_PEM TO ROLE ${OPERATOR_ROLE};

GRANT ROLE ${OPERATOR_ROLE} TO ROLE ${DEPLOYER_ROLE};
