-- Grants for Snowpipe REST caller (key-pair user). Run after pipe exists.
-- envsubst < spcs/sql/snowpipe_grants.sql | snow sql -c <conn>

USE ROLE ${DEPLOYER_ROLE};

GRANT USAGE ON DATABASE ${DB_NAME} TO ROLE ${SNOWPIPE_REST_ROLE};
GRANT USAGE ON SCHEMA ${DB_NAME}.${SCHEMA} TO ROLE ${SNOWPIPE_REST_ROLE};
GRANT USAGE ON SCHEMA ${DB_NAME}.${DATA_SCHEMA} TO ROLE ${SNOWPIPE_REST_ROLE};

GRANT READ ON STAGE ${DB_NAME}.${SCHEMA}.BEXIO_INGEST_STAGE TO ROLE ${SNOWPIPE_REST_ROLE};
GRANT INSERT ON TABLE ${DB_NAME}.${DATA_SCHEMA}.BEXIO_PIPE_LANDING TO ROLE ${SNOWPIPE_REST_ROLE};
GRANT OPERATE ON PIPE ${DB_NAME}.${SCHEMA}.BEXIO_JSON_PIPE TO ROLE ${SNOWPIPE_REST_ROLE};
GRANT MONITOR ON PIPE ${DB_NAME}.${SCHEMA}.BEXIO_JSON_PIPE TO ROLE ${SNOWPIPE_REST_ROLE};

GRANT ROLE ${SNOWPIPE_REST_ROLE} TO USER ${SNOWPIPE_REST_USER};
