-- Step 1a: Create roles (USERADMIN)
USE ROLE USERADMIN;

CREATE ROLE IF NOT EXISTS PRD_BEXIO_ETL_ADMIN
  COMMENT = 'Manages bexio ETL schemas, secrets, network rules, masking policies';

CREATE ROLE IF NOT EXISTS PRD_BEXIO_ETL_OPERATOR
  COMMENT = 'Executes and monitors bexio ETL job services';

CREATE ROLE IF NOT EXISTS PRD_BEXIO_DATA_READER
  COMMENT = 'Read-only access to bexio landing data in ERP.PRD_BEXIO';

-- Step 1b: Wire role hierarchy (SECURITYADMIN — has MANAGE GRANTS)
USE ROLE SECURITYADMIN;

GRANT ROLE PRD_BEXIO_ETL_OPERATOR TO ROLE PRD_BEXIO_ETL_ADMIN;
GRANT ROLE PRD_BEXIO_DATA_READER  TO ROLE PRD_BEXIO_ETL_ADMIN;
GRANT ROLE PRD_BEXIO_ETL_ADMIN    TO ROLE SYSADMIN;

-- Step 1c: BIND SERVICE ENDPOINT is account-level, requires ACCOUNTADMIN
USE ROLE ACCOUNTADMIN;

GRANT BIND SERVICE ENDPOINT ON ACCOUNT TO ROLE PRD_BEXIO_ETL_ADMIN;
