-- Step 3: Grants (SECURITYADMIN — MANAGE GRANTS)
USE ROLE SECURITYADMIN;

GRANT USAGE ON DATABASE ERP                TO ROLE PRD_BEXIO_DATA_READER;
GRANT USAGE ON SCHEMA   ERP.PRD_BEXIO     TO ROLE PRD_BEXIO_DATA_READER;
GRANT SELECT ON ALL TABLES IN SCHEMA ERP.PRD_BEXIO    TO ROLE PRD_BEXIO_DATA_READER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA ERP.PRD_BEXIO TO ROLE PRD_BEXIO_DATA_READER;

GRANT USAGE ON DATABASE ERP               TO ROLE PRD_BEXIO_ETL_OPERATOR;
GRANT USAGE  ON SCHEMA ERP.PRD_INFRA       TO ROLE PRD_BEXIO_ETL_OPERATOR;
GRANT CREATE SERVICE ON SCHEMA ERP.PRD_INFRA TO ROLE PRD_BEXIO_ETL_OPERATOR;
