-- Compute pools require ACCOUNTADMIN on this account (SYSADMIN lacks CREATE COMPUTE POOL)
USE ROLE ACCOUNTADMIN;

CREATE COMPUTE POOL IF NOT EXISTS PRD_BEXIO_COMPUTE_POOL
  MIN_NODES          = 1
  MAX_NODES          = 1
  INSTANCE_FAMILY    = CPU_X64_XS
  AUTO_RESUME        = TRUE
  AUTO_SUSPEND_SECS  = 300
  COMMENT            = 'Single-node XS pool for daily bexio ETL job';

GRANT USAGE ON COMPUTE POOL PRD_BEXIO_COMPUTE_POOL TO ROLE PRD_BEXIO_ETL_ADMIN;
GRANT USAGE ON COMPUTE POOL PRD_BEXIO_COMPUTE_POOL TO ROLE PRD_BEXIO_ETL_OPERATOR;
