spec:
  containers:
  - name: bexio-etl
    image: /ERP/PRD_INFRA/BEXIO_IMAGES/bexio-dlt-connector:v1.0
    env:
      BEXIO_DLT_DESTINATION: snowflake
      BEXIO_DLT_DATASET_NAME: PRD_BEXIO
      BEXIO_DLT_PIPELINE_NAME: bexio_pipeline
      DESTINATION_DATABASE: ERP
      DESTINATION_WAREHOUSE: ANALYTICS
      DESTINATION_ROLE: PRD_BEXIO_ETL_OPERATOR
      BEXIO_DATA_DIR: /home/appuser/data
      DESTINATION__SNOWFLAKE__CREDENTIALS__HOST: es10286-marketplace.snowflakecomputing.com
      DESTINATION__SNOWFLAKE__CREDENTIALS__ACCOUNT: es10286-marketplace
      DESTINATION__SNOWFLAKE__CREDENTIALS__DATABASE: ERP
      DESTINATION__SNOWFLAKE__CREDENTIALS__WAREHOUSE: ANALYTICS
      DESTINATION__SNOWFLAKE__CREDENTIALS__ROLE: PRD_BEXIO_ETL_OPERATOR
      DESTINATION__SNOWFLAKE__CREDENTIALS__AUTHENTICATOR: oauth
    secrets:
    - snowflakeSecret:
        objectName: ERP.PRD_SECRETS.BEXIO_CLIENT_ID
      secretKeyRef: secret_string
      envVarName: BEXIO_CLIENT_ID
    - snowflakeSecret:
        objectName: ERP.PRD_SECRETS.BEXIO_CLIENT_SECRET
      secretKeyRef: secret_string
      envVarName: BEXIO_CLIENT_SECRET
    - snowflakeSecret:
        objectName: ERP.PRD_SECRETS.BEXIO_REFRESH_TOKEN
      secretKeyRef: secret_string
      envVarName: BEXIO_REFRESH_TOKEN
    resources:
      requests:
        memory: 1Gi
        cpu: 0.5
      limits:
        memory: 2Gi
        cpu: 1
  logExporters:
    eventTableConfig:
      logLevel: INFO
