-- EAI is account-level — ACCOUNTADMIN is the only correct role here
USE ROLE ACCOUNTADMIN;

CREATE OR REPLACE EXTERNAL ACCESS INTEGRATION BEXIO_ETL_EAI
  ALLOWED_NETWORK_RULES     = (ERP.PRD_INFRA.BEXIO_EGRESS_RULE)
  ALLOWED_AUTHENTICATION_SECRETS = (
    ERP.PRD_SECRETS.BEXIO_CLIENT_ID,
    ERP.PRD_SECRETS.BEXIO_CLIENT_SECRET,
    ERP.PRD_SECRETS.BEXIO_REFRESH_TOKEN
  )
  ENABLED = TRUE
  COMMENT = 'External access for bexio ETL — egress to api.bexio.com and auth.bexio.com';

GRANT USAGE ON INTEGRATION BEXIO_ETL_EAI TO ROLE PRD_BEXIO_ETL_OPERATOR;
