USE ROLE PRD_BEXIO_ETL_OPERATOR;

CREATE STAGE IF NOT EXISTS ERP.PRD_INFRA.BEXIO_SPECS
  COMMENT = 'Stores SPCS job spec YAML files for bexio ETL';

-- Upload the spec file to the stage before running:
--   PUT file://deploy/07_job_spec.yaml @ERP.PRD_INFRA.BEXIO_SPECS AUTO_COMPRESS=FALSE;

CREATE OR REPLACE TASK ERP.PRD_INFRA.BEXIO_DAILY_ETL
  WAREHOUSE = ANALYTICS
  SCHEDULE  = 'USING CRON 0 6 * * * Europe/Zurich'
  COMMENT   = 'Daily bexio ETL job — runs at 06:00 Zurich time'
AS
  EXECUTE JOB SERVICE
    IN COMPUTE POOL PRD_BEXIO_COMPUTE_POOL
    NAME = ERP.PRD_INFRA.BEXIO_ETL_DAILY
    EXTERNAL_ACCESS_INTEGRATIONS = (BEXIO_ETL_EAI)
    QUERY_WAREHOUSE = ANALYTICS
    FROM @ERP.PRD_INFRA.BEXIO_SPECS
    SPECIFICATION_FILE = '07_job_spec.yaml';

ALTER TASK ERP.PRD_INFRA.BEXIO_DAILY_ETL RESUME;
